# Generated by Django 5.1.1 on 2024-09-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('banco', models.CharField(max_length=50)),
                ('chave_pix', models.CharField(max_length=100)),
            ],
        ),
    ]
