# Generated by Django 5.1.1 on 2025-01-01 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_renda', '0001_initial'),
        ('renda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renda',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria_renda.categoriarenda'),
        ),
    ]
