# Generated by Django 5.1.1 on 2025-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0003_renda_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renda',
            name='mes',
        ),
    ]
