# Generated by Django 5.1.1 on 2025-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0004_remove_renda_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='renda',
            name='valor_disponivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Disponível'),
        ),
    ]
