# Generated by Django 5.1.1 on 2025-01-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0003_despesa_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='mes',
        ),
    ]
