# Generated by Django 5.1.1 on 2025-01-05 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_remove_despesa_mes'),
        ('politico', '0003_politico_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='politico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='politico.politico'),
        ),
    ]
