# Generated by Django 5.1.1 on 2025-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0005_alter_despesa_politico'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Renda'),
        ),
    ]
