# Generated by Django 5.1.1 on 2025-01-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0006_despesa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Despesa'),
        ),
    ]
