# Generated by Django 5.1.1 on 2025-01-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0007_alter_despesa_nome'),
        ('renda', '0005_renda_valor_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='renda_utilizada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renda.renda', verbose_name='Renda Utilizada'),
        ),
    ]
